<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="http://maven.apache.org/POM/4.0.0"
		 xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
	<parent>
		<artifactId>spring-cloud-tencent-examples</artifactId>
		<groupId>com.tencent.cloud</groupId>
		<version>${revision}</version>
		<relativePath>../pom.xml</relativePath>
	</parent>
	<modelVersion>4.0.0</modelVersion>

	<artifactId>tsf-example</artifactId>
	<name>Spring Cloud Tencent TSF Examples</name>
	<packaging>pom</packaging>

	<modules>
		<module>provider-demo</module>
		<module>consumer-demo-retry</module>
		<module>consumer-demo</module>
	</modules>
</project>
