spring:
  cloud:
    tencent:
      gateway:
        groups:
          group-callee:
            predicate:
              apiType: ms
              context: /group-callee
              namespace:
                key: null
                position: PATH
              service:
                key: null
                position: PATH
            routes:
              - host: null
                metadata: { }
                method: GET
                namespace: default
                path: /quickstart/callee/info
                service: QuickstartCalleeService
          group-caller:
            predicate:
              apiType: ms
              context: /group-caller
              namespace:
                key: null
                position: PATH
              service:
                key: null
                position: PATH
            routes:
              - host: null
                metadata: { }
                method: GET
                namespace: default
                path: /quickstart/**
                service: QuickstartCallerService
        routes:
          group-callee:
            filters:
              - Context=group-callee
            order: -1
            predicates:
              - Context=group-callee
              - Path=/group-callee/**
            uri: lb://group-callee # do not use "_".
          group-caller:
            filters:
              - Context=group-caller
            order: -1
            predicates:
              - Context=group-caller
              - Path=/group-caller/**
            uri: lb://group-caller # do not use "_".
