server:
  port: 48081
spring:
  application:
    name: QuickStartGatewayService
  config:
    import: optional:polaris
  cloud:
    tencent:
      plugin:
        scg:
          staining:
            enabled: true
            rule-staining:
              enabled: true
        router:
          feature-env:
            enabled: true
    polaris:
      address: grpc://119.91.66.223:8091
      namespace: default
      enabled: true
      circuitbreaker:
        enabled: true
      contract:
        exposure: true
        report:
          enabled: true
      admin:
        port: 28081
      stat:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
          'predicates[0]':
            name: Path
            args:
              patterns: '''/'' + serviceId + ''/**'''
          'filters[0]':
            name: RewritePath
            args:
              regexp: '''/'' + serviceId + ''/(?<remaining>.*)'''
              replacement: '''/$\{remaining}'''
      routes:
        - id: QuickstartCallerService
          uri: lb://QuickstartCallerService
          predicates:
            - Path=/QuickstartCallerService/**
          filters:
            - StripPrefix=1
        - id: QuickstartCalleeService
          uri: lb://QuickstartCalleeService
          predicates:
            - Path=/QuickstartCalleeService/**
          filters:
            - StripPrefix=1
logging:
  file:
    name: /sct-demo-logs/${spring.application.name}/root.log
  level:
    root: INFO
