server:
  port: 48090
spring:
  application:
    name: LaneRouterGatewayService
  config:
    import: optional:polaris
  cloud:
    polaris:
      address: grpc://119.91.66.223:8091
      namespace: default
      enabled: true
      contract:
        exposure: true
        report:
          enabled: true
      admin:
        port: 28081
      stat:
        enabled: true
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: true
              'predicates[0]':
                name: Path
                args:
                  patterns: '''/'' + serviceId + ''/**'''
              'filters[0]':
                name: RewritePath
                args:
                  regexp: '''/'' + serviceId + ''/(?<remaining>.*)'''
                  replacement: '''/$\{remaining}'''
          routes:
            - id: LaneRouterCallerService
              uri: lb://LaneCallerService
              predicates:
                - Path=/LaneCallerService/**
              filters:
                - StripPrefix=1
