name: License checker

on:
  push:
    branches:
      - 2025.1
      - 2025.0
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich
      - release/*
    paths-ignore:
      - '**.md'
  pull_request:
    branches:
      - 2025.1
      - 2025.0
      - 2024
      - 2023
      - 2022
      - 2021
      - 2020
      - hoxton
      - greenwich
      - release/*
    paths-ignore:
      - '**.md'
jobs:
  check-license:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codes
        uses: actions/checkout@v6
      - name: Check License Header
        uses: apache/skywalking-eyes@v0.8.0
